---
# --- Metadatos Básicos ---
title: "Análisis Descriptivo de los Factores Determinantes en los Cultivos"
author:
   - Joshua Santeliz
   - Miguel Urbina
   - 
date: "Febrero 2026"

# --- Metadatos Específicos de Plantilla ---
degree: "Computación I"
director: 
  - Jesus Ochoa 
  - Oliver Triveño
lugar: "Caracas"
facultad: 
  - Facultad de Ciencias Económicas y Sociales
  - Escuela de Estadistica y Ciencias Actuariales
# Ruta al escudo (relativa al archivo .Rmd)
escudo: "Latex/Classes/Escudos/faces"

# --- Bibliografía ---
bibliography: bibliografia.bib

# --- Configuración de Salida ---
output: 
  pdf_document:
    template: template.tex  # Llamamos al archivo de plantilla
    keep_tex: true                 # Útil para ver errores si ocurren
    toc: true                      # Generar índice
    number_sections: true
    citation_package: natbib       # Importante: forzar natbib porque tu plantilla lo usa

# --- Resumen (Abstract) ---
abstract: |
  Resumen del trabajo de investigación...
---

```{r setup, include=FALSE}
# Configuración global de chunks
knitr::opts_chunk$set(
  echo = FALSE,        # Mostrar código
  warning = FALSE,    # Ocultar advertencias
  message = FALSE,    # Ocultar mensajes de carga
  fig.align = "center",
  out.width = "90%",
  fig.pos = "H",
  out.extra = ""
)

# Cargar librerías necesarias
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
```

\chapter*{Introducción}

Introducción del trabajo de investigación

\chapter{Planteamiento del Problema}
En el mundo agrícola hay muchos temas por tratar, desde la salud nutricional hasta la gastronomía industrial, siendo temas de vital importancia para la vida humana. En este estudio analizaremos específicamente a la agricultura de la India en el ámbito del cultivo, resaltando que un manejo eficiente no solo garantiza cosechas óptimas, sino que genera seguridad alimentaria y eleva la calidad de vida de las personas.
Los cultivos son influenciados por factores como el clima, los ciclos agrícolas, fertilizantes y pesticida, estos factores son importantes ya que a las empresas les interesas esas influencias para mejorar su gestión de inversión, bajando la incertidumbre al describir estas influencias.
\

Por lo antes mencionado surgen problemas por ejemplo en la parte del clima como fenómenos naturales, problemas de contaminación que podría afectar ya sea al clima o a los mismos cultivos, estos problemas se resuelven luego de modelar esta investigación donde podremos comprender mejor la situación y se recomendará posibles decisiones a tomar. Debido a esto, se plantea las siguientes preguntas de investigación:\


\textbf{1.}		¿De qué manera influye el clima en la calidad de los cultivos?\

\textbf{2.}		¿Por qué son necesario los fertilizantes y los pesticidas en una temporada de cultivo? ¿Afectaría la salud de la población de la India a nivel nutricional? \

\textbf{3.}	¿Cuáles son los cultivos que más se dan según las temporadas del año?\


\section{Justificación}

La justificación de este trabajo de investigación reside en la necesidad de aplicar técnicas estadísticas rigurosas y herramientas de software como R y Python para mitigar la incertidumbre de sembrar los cultivos en el sector agrícola de la India.
Desde el punto de vista práctico, los resultados permitirán a las Industrias tomar decisiones basadas en datos (Data-Driven Decisions) sobre que materiales invertir o en qué temporada del año se debe desarrollar. Con una metodología replicable utilizando R y LaTeX para el análisis exploratorio y descriptivo de grandes volúmenes de datos.
\

\section{Objetivos}
 
\subsection{Objetivo General}
\begin{itemize}
  \item{Realizar un análisis estadístico descriptivo de datos de cultivos en diferentes temporadas de la India durante el período 2010-2020.  para identificar y describir las características más influyentes en los cultivos.}
\end{itemize}

\subsection{Objetivos Específicos}
\begin{itemize}
  \item{1.	Analizar la variabilidad pluviométrica estacional mediante el uso de indicadores estadísticos, con el fin de determinar una óptima gestión del recurso hídrico en cada ciclo de cultivo}
  \item{2.	Observar la distribución de los factores que afectan a los cultivos por temporada del año.}
  \item{3.	Categorizar temporadas de mayor y menor demanda tanto de pesticidas como de fertilizantes}
\end{itemize}


\section{Cobertura}

\subsection{Horizontal}

La cobertura horizontal abarca las características de cada cultivo registrado, donde se consideran las dimensiones descriptivas del cultivo y las métricas de rendimiento agrícola.\

\begin{table}[ht]
\centering
\caption{Variables consideradas} 
\resizebox{10cm}{!} {
\begin{tabular}{ccc}
  \hline
\ \ \ \ \ NOMBRE DE LA VARIABLE \\ 
  \hline
   VARIABLE 1 \\ 
VARIABLE 2\\ 
VARIABLE n\\ 
   \hline
\end{tabular}
}
\end{table}

\subsection{Vertical}

Describir la cobertura Vertical del trabajo de investigación


\section{Periodo de Referencia}

Describir la fuente y el Periodo de Referencia utilizado en el trabajo de investigación

\section{Variables}

Describir la variable en estudio en el trabajo de investigación

\chapter{Marco Teórico}


\section{Bases Teóricas}

Resumen de las bases teoricas explicadas en el capitulo y su importancia\

\subsection{Definición 1}

Descripción de la definición 1\

\subsection{Definición 2}

Descripción de la definición 2\

\subsection{Definición n}

Descripción de la definición n\


\chapter{Marco Metódico}
En esta sección se presentan las metodologías y/o test necesarios relacionados con la práctica divulgada en el marco teórico, así como las fuentes de datos.
 
\section{Bases metódicas utilizadas en el trabajo de investigación}

Desarrollo\

\subsection{Item 1}

Descripción\

\subsection{Item 2}

Descripción\

\subsubsection{Item 2.2}

Descripción\

\subsection{Item n}

Descripción\

\chapter{Análisis de Resultados}

{\small Este capítulo presenta los resultados obtenidos al aplicar las metodologías descritas en el capítulo anterior, así como del análisis estadístico descriptivo de las variables estudiadas y las ventajas y desventajas al aplicar dichos tests.}

\section{Presentación de resultados 1}

Descripción\

\section{Presentación de resultados 2}

Descripción\

\section{Presentación de resultados n}

Descripción\

\chapter{Conclusiones y Recomendaciones}

\textbf{1.-} Conclusion 1 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 1 del trabajo de investigación.\

\textbf{2.-} Conclusion 2 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 2 del trabajo de investigación.\

\textbf{n.-} Conclusion n del trabajo de investigación.\

\textbf{Recomendación} Recomendación n del trabajo de investigación.\

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

\chapter{Anexo A}

\chapter{Anexo B}

\chapter{Anexo C}

